"""Add last_full_scan timestamp to monitored url

Revision ID: 0ba4d6096458
Revises: de8a51285be8
Create Date: 2025-04-09 19:47:37.720983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ba4d6096458'
down_revision = 'de8a51285be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitored_url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_full_scan', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitored_url', schema=None) as batch_op:
        batch_op.drop_column('last_full_scan')

    # ### end Alembic commands ###
