"""Initial migration

Revision ID: 4d6ea032baae
Revises: 
Create Date: 2025-04-10 17:49:11.688363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d6ea032baae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('monitored_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ssl_expiry_date', sa.DateTime(), nullable=True),
    sa.Column('domain_expiry_date', sa.DateTime(), nullable=True),
    sa.Column('last_advanced_check', sa.DateTime(), nullable=True),
    sa.Column('last_successful_advanced_check', sa.DateTime(), nullable=True),
    sa.Column('last_full_scan', sa.DateTime(), nullable=True),
    sa.Column('last_scan_ip', sa.String(length=45), nullable=True),
    sa.Column('last_scan_rdap', sa.Text(), nullable=True),
    sa.Column('last_scan_dns', sa.Text(), nullable=True),
    sa.Column('last_scan_traceroute', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitored_url', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitored_url_added_at'), ['added_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitored_url_url'), ['url'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitored_url_user_id'), ['user_id'], unique=False)

    op.create_table('monitoring_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.String(length=200), nullable=True),
    sa.Column('monitored_url_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['monitored_url_id'], ['monitored_url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_log_monitored_url_id'), ['monitored_url_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_log_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_apscheduler_jobs_next_run_time')

    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_apscheduler_jobs_next_run_time', ['next_run_time'], unique=False)

    with op.batch_alter_table('monitoring_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_monitoring_log_monitored_url_id'))

    op.drop_table('monitoring_log')
    with op.batch_alter_table('monitored_url', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitored_url_user_id'))
        batch_op.drop_index(batch_op.f('ix_monitored_url_url'))
        batch_op.drop_index(batch_op.f('ix_monitored_url_added_at'))

    op.drop_table('monitored_url')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
