"""Add ssl and domain expiry fields to monitored url

Revision ID: de8a51285be8
Revises: 398f27ba39fb
Create Date: 2025-04-09 19:34:51.433270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8a51285be8'
down_revision = '398f27ba39fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitored_url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ssl_expiry_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('domain_expiry_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_advanced_check', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitored_url', schema=None) as batch_op:
        batch_op.drop_column('last_advanced_check')
        batch_op.drop_column('domain_expiry_date')
        batch_op.drop_column('ssl_expiry_date')

    # ### end Alembic commands ###
